### PR TITLE
Extract mock annotations/classes/methods into Lint options

### PR DESCRIPTION
**Pull request by SimonMarquis**
###  Summary

This PR implements support for other mocking frameworks through Lint options:
-  #99

### Requirements

* [x] I've read and understood the [Contributing Guidelines](https://github.com/{project_slug}/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

> The following point can be removed after setting up CI (such as Travis) with coverage reports (such as Codecov)

* [ ] I've written tests to cover the new code and functionality included in this PR.

> The following point can be removed after setting up a CLA reporting tool such as cla-assistant.io

* [x] I've read, agree to, and signed the [Contributor License Agreement (CLA)](https://cla-assistant.io/{project_slug}).

### CODE REVIEW

**Comment by ZacSweers** [comment]
@SimonMarquis are you still planning to pursue this?

**Comment by SimonMarquis** [comment]
Yes! I couldn't find time for this in the last weeks. But I'll try to add tests this weekend and see how classes & methods checks could be merged.

**Comment by ZacSweers** [comment]
Sounds good!

**Comment by SimonMarquis** [comment]
@ZacSweers I've added the `MockDetectorOptionsTest` test class, but I've a hard time figuring out how to merge methods and classes.
I tried to find a way to access the fqn of the `UCallExpression`, but did not find anything :/

**Comment by ZacSweers** [comment]
> I tried to find a way to access the fqn of the UCallExpression

I would expect this to work like so
- `node.resolve()` to get the underlying `UMethod`
- fqcn would be the method's package name + simple name

Note that the fqcn likely includes the enclosing synthetic class for top-level functions

**Comment by ZacSweers** [comment]
@SimonMarquis we'd like to merge this soon, do you still want to contribute it?

**Comment by SimonMarquis** [comment]
Oh, indeed.
But it seem's that MockK's reified `mockk` method would be resolved to `io.mockk.MockKKt.mockk`, while non-reified `mockkClass` would be resolved to `io.mockk.mockkClass`.
I'm not sure if this could be considered a good API though.
Also, I'm sorry, I wont be able to dedicate enough time to debug this in the near future.

**Comment by ZacSweers** [comment]
Got it all working 👍

**Review by ZacSweers — APPROVED** [review]

**Comment by SimonMarquis** [comment]
Thanks a lot for completing this PR!

**Pull request merged**
